<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="USER-20180223JL" ignored="0" name="Command line test" tests="8" failures="2" timestamp="16 六月 2018 08:36:55 GMT" time="0.099" errors="0">
  <testcase name="test1" time="0.005" classname="test.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Test1.test1(Test1.java:25)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.0" classname="test.Test1"/>
  <testcase name="test1" time="0.001" classname="test.TestNGDemo"/>
  <testcase name="TestException" time="0.0" classname="test.TestNGDemo2">
    <failure type="org.testng.TestException" message="
Expected exception of type class java.io.IOException but got java.lang.ArithmeticException: / by zero">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.io.IOException but got java.lang.ArithmeticException: / by zero
Caused by: java.lang.ArithmeticException: / by zero
at test.TestNGDemo2.TestException(TestNGDemo2.java:23)
... 29 more
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- TestException -->
  <testcase name="divisionWithException" time="0.0" classname="test.TestNGDemo2"/>
  <testcase name="test" time="0.001" classname="test.TestParaDemo"/>
  <testcase name="test" time="0.0" classname="test.TestParaDemo"/>
  <testcase name="test" time="0.0" classname="test.TestParaDemo"/>
</testsuite> <!-- Command line test -->
